version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt update	
      - apt install -y python3-pip
  build:
    commands:
      - pip3 install -r log-parse/requirements.txt -t log-parse/src/
      - pip3 install -r ems-report/requirements.txt -t ems-report/src/
      - aws cloudformation package --template-file cloudformation-wrapper.yaml --s3-bucket $BUCKET --s3-prefix $PREFIX --output-template-file cloudformation-final.yaml
artifacts:
  type: zip
  files:
    - cloudformation-final.yaml
