AWSTemplateFormatVersion: 2010-09-09

Parameters:

  ElasticSearchCidrIp:
    Type: String

  LogBucket:
    Type: String

  Maturity:
    Description: Value for MATURITY tag to be applied to all taggable resources
    Type: String
    Default: DEV
    AllowedValues:
    - DEV
    - TEST
    - PROD

Outputs:

  KibanaUrl:
    Value: !GetAtt MainStack.Outputs.KibanaUrl

Resources:

  MainStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Tags:
      - Key: MATURITY
        Value: !Ref Maturity
      - Key: APPLICATION
        Value: GRFN-LOGGING
      Parameters:
        Name: !Ref AWS::StackName
        ElasticSearchCidrIp: !Ref ElasticSearchCidrIp
        LogBucket: !Ref LogBucket
      TemplateURL: cloudformation-main.yaml
